name: 'Cache npm'
description: 'Setup cache for npm'
inputs:
  cache-enabled:
    description: 'NPM cache enabled. If unset, the cache will be enabled if a package-lock.json file is found.'
    required: false
  cache-path:
    description: 'NPM cache directory path'
    required: false
runs:
  using: 'composite'
  steps:
    - name: ⚙️ Configure npm cache path
      shell: bash
      run: |
        if [ -n "${{ inputs.cache-path }}" ]; then
          NPM_CONFIG_CACHE="${{ inputs.cache-path }}"
        else
          NPM_CONFIG_CACHE="$HOME/.npm"
        fi
        echo "NPM_CONFIG_CACHE=$NPM_CONFIG_CACHE" >> "$GITHUB_ENV"
        echo "npm_config_cache=$NPM_CONFIG_CACHE" >> "$GITHUB_ENV"

    - name: 📦 Cache npm
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: ${{ env.NPM_CONFIG_CACHE }}
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
      if: (inputs.cache-enabled == 'true' || (inputs.cache-enabled != 'false' && hashFiles('**/package-lock.json') != ''))
