name: 'Cache npm'
description: 'Setup cache for npm'
inputs:
  cache-enabled:
    description: 'NPM cache enabled. If unset, the cache will be enabled if a package-lock.json file is found.'
    required: false
  cache-path:
    description: 'NPM cache directory path'
    required: false
    default: ~/.npm
runs:
  using: 'composite'
  steps:
    - name: ⚙️ Configure npm cache path
      shell: bash
      run: |
        echo "NPM_CONFIG_CACHE=${{ inputs.cache-path }}" >> "$GITHUB_ENV"
        echo "npm_config_cache=${{ inputs.cache-path }}" >> "$GITHUB_ENV"
      if: (inputs.cache-enabled == 'true' || (inputs.cache-enabled != 'false' && hashFiles('**/package-lock.json') != ''))

    - name: 📦 Cache npm
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-npm-
      if: (inputs.cache-enabled == 'true' || (inputs.cache-enabled != 'false' && hashFiles('**/package-lock.json') != ''))
