name: 'Setup Node package manager'
description: 'Enable Corepack based on package.json packageManager'
runs:
  using: 'composite'
  steps:
    - name: ⚙️ Install Node package manager
      shell: bash
      run: |
        package_manager=$(jq -r '.packageManager // empty' package.json)
        if [ -n "$package_manager" ]; then
          # Install corepack if not working
          if ! corepack -v >/dev/null 2>&1; then
            npm install -g corepack
          fi

          echo "Package manager: $package_manager"
          corepack enable

          if command -v asdf >/dev/null 2>&1; then
            asdf reshim nodejs
          fi
        fi
      if: hashFiles('package.json') != ''
