name: 'Cache bun'
description: 'Setup cache for bun'
inputs:
  cache-enabled:
    description: 'Bun cache enabled. If unset, the cache will be enabled if a bun.lock or bun.lockb file is found.'
    required: false
  cache-path:
    description: 'Bun cache directory path'
    required: false
    default: ~/.bun/install/cache
runs:
  using: 'composite'
  steps:
    - name: ⚙️ Configure bun cache path
      shell: bash
      run: |
        echo "BUN_INSTALL_CACHE_DIR=${{ inputs.cache-path }}" >> "$GITHUB_ENV"
      if: inputs.cache-path != ''

    - name: 📦 Cache bun
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock', '**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-
      if: (inputs.cache-enabled == 'true' || (inputs.cache-enabled != 'false' && inputs.cache-path != '' && (hashFiles('**/bun.lock') != '' || hashFiles('**/bun.lockb') != '')))
