name: 'Cache bun'
description: 'Setup cache for bun'
inputs:
  cache-enabled:
    description: 'Bun cache enabled. If unset, the cache will be enabled if a bun.lock or bun.lockb file is found.'
    required: false
  cache-path:
    description: 'Bun cache directory path'
    required: false
runs:
  using: 'composite'
  steps:
    - name: ⚙️ Configure bun cache path
      shell: bash
      run: |
        if [ -n "${{ inputs.cache-path }}" ]; then
          BUN_INSTALL_CACHE_DIR="${{ inputs.cache-path }}"
        else
          BUN_INSTALL_CACHE_DIR="$HOME/.bun/install/cache"
        fi
        echo "BUN_INSTALL_CACHE_DIR=$BUN_INSTALL_CACHE_DIR" >> "$GITHUB_ENV"

    - name: 📦 Cache bun
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5
      with:
        path: ${{ env.BUN_INSTALL_CACHE_DIR }}
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock', '**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-
      if: (inputs.cache-enabled == 'true' || (inputs.cache-enabled != 'false' && (hashFiles('**/bun.lock') != '' || hashFiles('**/bun.lockb') != '')))
