name: 'Cache pnpm'
description: 'Setup cache for pnpm'
inputs:
  cache-enabled:
    description: 'pnpm cache enabled. If unset, the cache will be enabled if a pnpm-lock.yaml file is found.'
    required: false
  cache-path:
    description: 'pnpm store directory path'
    required: false
    default: ~/.pnpm-store
runs:
  using: 'composite'
  steps:
    - name: ⚙️ Configure pnpm store path
      shell: bash
      run: |
        pnpm config set store-dir "${{ inputs.cache-path }}"
      if: (inputs.cache-enabled == 'true' || (inputs.cache-enabled != 'false' && hashFiles('**/pnpm-lock.yaml') != ''))

    - name: 📦 Cache pnpm
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
      with:
        path: ${{ inputs.cache-path }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-
      if: (inputs.cache-enabled == 'true' || (inputs.cache-enabled != 'false' && hashFiles('**/pnpm-lock.yaml') != ''))
