name: 'Cache pnpm'
description: 'Setup cache for pnpm'
inputs:
  cache-enabled:
    description: 'pnpm cache enabled. If unset, the cache will be enabled if a pnpm-lock.yaml file is found.'
    required: false
  cache-path:
    description: 'pnpm store directory path'
    required: false
runs:
  using: 'composite'
  steps:
    - name: ⚙️ Configure pnpm store path
      shell: bash
      run: |
        if [ -n "${{ inputs.cache-path }}" ]; then
          PNPM_STORE_DIR="${{ inputs.cache-path }}"
        else
          PNPM_STORE_DIR="$HOME/.pnpm-store"
        fi
        echo "PNPM_STORE_DIR=$PNPM_STORE_DIR" >> "$GITHUB_ENV"
        pnpm config set store-dir "$PNPM_STORE_DIR"

    - name: 📦 Cache pnpm
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
      with:
        path: ${{ env.PNPM_STORE_DIR }}
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-
      if: (inputs.cache-enabled == 'true' || (inputs.cache-enabled != 'false' && hashFiles('**/pnpm-lock.yaml') != ''))
