name: 'Cache yarn'
description: 'Setup cache for yarn'
inputs:
  cache-enabled:
    description: 'Yarn cache enabled. If unset, the cache will be enabled if a yarn.lock file is found.'
    required: false
  cache-path:
    description: 'Yarn cache directory path'
    required: false
runs:
  using: 'composite'
  steps:
    - name: ⚙️ Configure yarn cache path
      shell: bash
      # set YARN_CACHE_FOLDER and YARN_ENABLE_GLOBAL_CACHE environment variables for the rest of the job
      run: |
        if [ -n "${{ inputs.cache-path }}" ]; then
          YARN_CACHE_FOLDER="${{ inputs.cache-path }}"
        else
          YARN_CACHE_FOLDER="$HOME/.yarn/cache"
        fi
        echo "YARN_CACHE_FOLDER=$YARN_CACHE_FOLDER" >> "$GITHUB_ENV"
        echo "YARN_ENABLE_GLOBAL_CACHE=false" >> "$GITHUB_ENV"

    - name: 📦 Cache yarn
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
      with:
        path: ${{ env.YARN_CACHE_FOLDER }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
      if: (inputs.cache-enabled == 'true' || (inputs.cache-enabled != 'false' && hashFiles('**/yarn.lock') != ''))
