name: Test Integration
on:
  merge_group: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        fixture:
          - name: bun
          - name: node
          - name: npm
          - name: python
          - name: pnpm
          - name: ruby
          - name: yarn
    steps:
      - name: ⬇️ Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: 🧹 Prepare workspace for fixture
        shell: bash
        run: |
          rm -f package.json pnpm-lock.yaml yarn.lock package-lock.json bun.lock bun.lockb uv.lock pyproject.toml requirements.txt setup.py
          cp -R ".github/test-fixtures/${{ matrix.fixture.name }}/." .

      - name: 🛠️ Setup tools
        uses: ./setup-tools
        if: hashFiles('.tool-versions') != ''

      - name: 🛠️ Setup Node package manager
        uses: ./setup-corepack
        if: hashFiles('package.json') != ''

      - name: ✅ Run fixture verification script
        shell: bash
        run: bash ./test.sh
